                   function FUCKUTHIEF() {
                   document.write('<ul id="myUL" class="">');


document.write('      <li id="home" class="btn">');
document.write('        <a href="https://www.google.com/url?sa=t&source=web&rct=j&url=https://aliwixplay.tn/app&ved=2ahUKEwjl__DQxJz7AhXYX_EDHcDBA8AQjBB6BAgHEAM&usg=AOvVaw1goJFtarQjpv9Qguuidr-F"><span style="font-size:30px">📱</span>download mobile app !</a>');
document.write('      </li>');
document.write('      <li id="1" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=0" target="iframe_007"><font id="des">Bein Sports News</font> <font id="mob">Bein Sports News</font></a>');
document.write('      </li>');
document.write('      <li id="2" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=01" target="iframe_007"><font id="des">Bein Sports HD</font> <font id="mob">Bein Sports HD</font></a>');
document.write('      </li>');
document.write('      <li id="3" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=8" target="iframe_007"><font id="des">beIN PREMIUM 1</font> <font id="mob">beIN PREMIUM 1</font></a>');
document.write('      </li>');
document.write('      <li id="4" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=9" target="iframe_007"><font id="des">beIN PREMIUM 2</font> <font id="mob">beIN PREMIUM 2</font></a>');
document.write('      </li>');
document.write('      <li id="5" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=10" target="iframe_007"><font id="des">beIN PREMIUM 3</font> <font id="mob">beIN PREMIUM 3</font></a>');
document.write('      </li>');
document.write('      <li id="6" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=1" target="iframe_007"><font id="des">Alshoula Sport 1 HD</font> <font id="mob">Alshoula Sport 1 HD</font></a>');
document.write('      </li>');
document.write('      <li id="7" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=2" target="iframe_007"><font id="des">Alshoula Sport 2 HD</font> <font id="mob">Alshoula Sport 2 HD</font></a>');
document.write('      </li>');
document.write('      <li id="8" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=3" target="iframe_007"><font id="des">Alshoula Sport 3 HD</font> <font id="mob">Alshoula Sport 3 HD</font></a>');
document.write('      </li>');
document.write('      <li id="9" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=4" target="iframe_007"><font id="des">Alshoula Sport 4 HD</font> <font id="mob">Alshoula Sport 4 HD</font></a>');
document.write('      </li>');
document.write('      <li id="10" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=14" target="iframe_007"><font id="des">beIN SPORT 01 HD</font> <font id="mob">beIN SPORT 01 HD</font></a>');
document.write('      </li>');
document.write('      <li id="11" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=15" target="iframe_007"><font id="des">beIN SPORT 02 HD</font> <font id="mob">beIN SPORT 02 HD</font></a>');
document.write('      </li>');
document.write('      <li id="12" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=16" target="iframe_007"><font id="des">beIN SPORT 03 HD</font> <font id="mob">beIN SPORT 03 HD</font></a>');
document.write('      </li>');
document.write('      <li id="13" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=17" target="iframe_007"><font id="des">beIN SPORT 04 HD</font> <font id="mob">beIN SPORT 04 HD</font></a>');
document.write('      </li>');
document.write('      <li id="43" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=5" target="iframe_007"><font id="des">beIN SPORT 05 HD</font> <font id="mob">beIN SPORT 05 HD</font></a>');
document.write('      </li>');
document.write('      <li id="44" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=6" target="iframe_007"><font id="des">beIN SPORT 06 HD</font> <font id="mob">beIN SPORT 06 HD</font></a>');
document.write('      </li>');
document.write('      <li id="45" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=7" target="iframe_007"><font id="des">beIN SPORT 07 HD</font> <font id="mob">beIN SPORT 07 HD</font></a>');
document.write('      </li>');
document.write('      <li id="15" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=23" target="iframe_007"><font id="des">Bein Sport AFC</font> <font id="mob">Bein Sport AFC</font></a>');
document.write('      </li>');
document.write('      <li id="16" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=24" target="iframe_007"><font id="des">Bein Sport AFC 1</font> <font id="mob">Bein Sport AFC 1</font></a>');
document.write('      </li>');
document.write('      <li id="17" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=25" target="iframe_007"><font id="des">Bein Sport AFC 2</font> <font id="mob">Bein Sport AFC 2</font></a>');
document.write('      </li>');
document.write('      <li id="18" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=26" target="iframe_007"><font id="des">Bein Sport AFC 3</font> <font id="mob">Bein Sport AFC 3</font></a>');
document.write('      </li>');
document.write('      <li id="19" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=44" target="iframe_007"><font id="des">Raya 1</font> <font id="mob">Raya 1</font></a>');
document.write('      </li>');
document.write('      <li id="20" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=45" target="iframe_007"><font id="des">Raya 2</font> <font id="mob">Raya 2</font></a>');
document.write('      </li>');
document.write('      <li id="21" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=46" target="iframe_007"><font id="des">Raya 3</font> <font id="mob">Raya 3</font></a>');
document.write('      </li>');
document.write('      <li id="14" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=34" target="iframe_007"><font id="des">Bein Sport FR 1</font> <font id="mob">Bein Sport FR 1</font></a>');
document.write('      </li>');
document.write('      <li id="22" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=35" target="iframe_007"><font id="des">Bein Sport FR 2</font> <font id="mob">Bein Sport FR 2</font></a>');
document.write('      </li>');
document.write('      <li id="23" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=36" target="iframe_007"><font id="des">Bein Sport FR 3</font> <font id="mob">Bein Sport FR 3</font></a>');
document.write('      </li>');
document.write('      <li id="24" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=31" target="iframe_007"><font id="des">StarzPlay SPORT 1</font> <font id="mob">StarzPlay SPORT 1</font></a>');
document.write('      </li>');
document.write('      <li id="25" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=32" target="iframe_007"><font id="des">StarzPlay SPORT 2</font> <font id="mob">StarzPlay SPORT 2</font></a>');
document.write('      </li>');
document.write('      <li id="26" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=33" target="iframe_007"><font id="des">StarzPlay SPORT 3</font> <font id="mob">StarzPlay SPORT 3</font></a>');
document.write('      </li>');
document.write('      <li id="27" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=27" target="iframe_007"><font id="des">KSA Sport 1</font> <font id="mob">KSA Sport 1</font></a>');
document.write('      </li>');
document.write('      <li id="28" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=28" target="iframe_007"><font id="des">KSA Sport +1</font> <font id="mob">KSA Sport +1</font></a>');
document.write('      </li>');
document.write('      <li id="29" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=29" target="iframe_007"><font id="des">KSA Sport 2</font> <font id="mob">KSA Sport 2</font></a>');
document.write('      </li>');
document.write('      <li id="30" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=30" target="iframe_007"><font id="des">KSA Sport +2</font> <font id="mob">KSA Sport +2</font></a>');
document.write('      </li>');
document.write('      <li id="31" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=37" target="iframe_007"><font id="des">Sport ISIA 1</font> <font id="mob">Sport ISIA 1</font></a>');
document.write('      </li>');
document.write('      <li id="32" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=38" target="iframe_007"><font id="des">Sport ISIA 2</font> <font id="mob">Sport ISIA 2</font></a>');
document.write('      </li>');
document.write('      <li id="33" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=39" target="iframe_007"><font id="des">Sport ISIA 3</font> <font id="mob">Sport ISIA 3</font></a>');
document.write('      </li>');
document.write('      <li id="34" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=40" target="iframe_007"><font id="des">Sport ISIA 4</font> <font id="mob">Sport ISIA 4</font></a>');
document.write('      </li>');
document.write('      <li id="35" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=41" target="iframe_007"><font id="des">Sport ISIA Gold</font> <font id="mob">Sport ISIA Gold</font></a>');
document.write('      </li>');
document.write('      <li id="36" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=42" target="iframe_007"><font id="des">Sport ISIA 5</font> <font id="mob">Sport ISIA 5</font></a>');
document.write('      </li>');
document.write('      <li id="37" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=43" target="iframe_007"><font id="des">Sport ISIA Plus</font> <font id="mob">Sport ISIA Plus</font></a>');
document.write('      </li>');
document.write('      <li id="38" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=47" target="iframe_007"><font id="des">SSC-7</font> <font id="mob">SSC-7</font></a>');
document.write('      </li>');
document.write('      <li id="39" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=48" target="iframe_007"><font id="des">AD SPORT 1</font> <font id="mob">AD SPORT 1</font></a>');
document.write('      </li>');
document.write('      <li id="40" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=11" target="iframe_007"><font id="des">BEIN SPORT MAX 1</font> <font id="mob">BEIN SPORT MAX 1</font></a>');
document.write('      </li>');
document.write('      <li id="41" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=11" target="iframe_007"><font id="des">BEIN SPORT MAX 2</font> <font id="mob">BEIN SPORT MAX 2</font></a>');
document.write('      </li>');
document.write('      <li id="42" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=11" target="iframe_007"><font id="des">BEIN SPORT MAX 3</font> <font id="mob">BEIN SPORT MAX 3</font></a>');
document.write('      </li>');
document.write('      <li id="42" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=11" target="iframe_007"><font id="des">BEIN SPORT MAX 4</font> <font id="mob">BEIN SPORT MAX 4</font></a>');
document.write('      </li>');
document.write('      <li id="46" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=11" target="iframe_007"><font id="des">bein prumium 1 Fhd</font> <font id="mob">bein prumium 1 Fhd</font></a>');
document.write('      </li>');
document.write('      <li id="47" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=12" target="iframe_007"><font id="des">bein prumium 2 Fhd</font> <font id="mob">bein prumium 2 Fhd</font></a>');
document.write('      </li>');
document.write('      <li id="48" class="btn">');
document.write('        <a href="https://foufank.tk:8443/chola/shoula.php?ch=13" target="iframe_007"><font id="des">bein prumium 3 Fhd</font> <font id="mob">bein prumium 3 Fhd</font></a>');
document.write('      </li>');



          document.write('    </ul>');
                                     }
