function FUCKUTHIEF(){
document.write('<ul id="matchKey">');
document.write('  <li class="menu2" tabindex="0" onclick="https(\aliwixplay.tn/live/hls/tf1.m3u8\)">');
document.write('    <img title="FRANCE " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <span>tf1</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\aliwixplay.tn/live/hls/tfx.m3u8\)">');
document.write('    <img title="FRANCE " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <span>tfx</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\aliwixplay.tn/live/hls/m6.m3u8\)">');
document.write('    <img title="FRANCE " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <span>m6</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\aliwixplay.tn/live/hls/arte.m3u8\)">');
document.write('    <img title="FRANCE " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <span>arte</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\aliwixplay.tn/live/hls/lci.m3u8\)">');
document.write('    <img title="FRANCE " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <span>lci</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\aliwixplay.tn/live/hls/tmc.m3u8\)">');
document.write('    <img title="FRANCE " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <span>tmc</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\aliwixplay.tn/live/hls/cnews.m3u8\)">');
document.write('    <img title="FRANCE " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <span>cnews</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\aliwixplay.tn/live/hls/cstar.m3u8\)">');
document.write('    <img title="FRANCE " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <img title="FRANCE " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <span>cstar</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="window.location.href=\'https://aliwixplay.rf.gd/script/aliwix/cast.php?ch=38834\'">');
document.write('    <img title="CANAL PLAY " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <span>canal play action</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="window.location.href=\'https://aliwixplay.rf.gd/script/aliwix/cast.php?ch=36682\'">');
document.write('    <img title="CANAL PLAY " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <span>canal play kids</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="window.location.href=\'https://aliwixplay.rf.gd/script/aliwix/cast.php?ch=39427\'">');
document.write('    <img title="CANAL PLAY " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <span>canal play family</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="window.location.href=\'https://aliwixplay.rf.gd/script/aliwix/cast.php?ch=36681\'">');
document.write('    <img title="CANAL PLAY " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <span>canal play ciné</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="window.location.href=\'https://aliwixplay.rf.gd/script/aliwix/cast.php?ch=39692\'">');
document.write('    <img title="CANAL PLAY " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <span>canal play film</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="window.location.href=\'https://aliwixplay.rf.gd/script/aliwix/cast.php?ch=39730\'">');
document.write('    <img title="CANAL PLAY " src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-cbnlewe0B7cVwBxZ8JFwjrEgwOsUfYsegg&usqp=CAU">');
document.write('    <span>canal play music</span>');
document.write('  </li>');
document.write('</ul>');

document.write('  <li class="menu2" tabindex="0" onclick="http(\service-stitcher-ipv4.clusters.pluto.tv/v1/stitch/embed/hls/channel/5f8ed0f17564a300082b676a/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=%7BUS_PRIVACY%7D&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&embedPartner=samsung-tvplus&gdprConsent=%7BTC_STRING%7D&gdpr=1\)">');
document.write('    <span>CINE</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="http(\service-stitcher-ipv4.clusters.pluto.tv/v1/stitch/embed/hls/channel/5f8ed1ff5c39700007e2204a/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=%7BUS_PRIVACY%7D&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&embedPartner=samsung-tvplus&gdprConsent=%7BTC_STRING%7D&gdpr=1\)">');
document.write('    <span>CINE Action</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="http(\service-stitcher-ipv4.clusters.pluto.tv/v1/stitch/embed/hls/channel/5f8ed168f72fcd0007e56269/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=%7BUS_PRIVACY%7D&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&embedPartner=samsung-tvplus&gdprConsent=%7BTC_STRING%7D&gdpr=1\)">');
document.write('    <span>CINE Retro</span>');
document.write('  </li>');

document.write('  <li class="menu2" tabindex="0" onclick="http(\service-stitcher-ipv4.clusters.pluto.tv/v1/stitch/embed/hls/channel/60812fc8539963000707d1e1/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=%7BUS_PRIVACY%7D&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&embedPartner=samsung-tvplus&gdprConsent=%7BTC_STRING%7D&gdpr=1\)">');
document.write('    <span>CINE Romance</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="http(\service-stitcher-ipv4.clusters.pluto.tv/v1/stitch/embed/hls/channel/60c34592c911890007f29a73/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=%7BUS_PRIVACY%7D&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&embedPartner=samsung-tvplus&gdprConsent=%7BTC_STRING%7D&gdpr=1\)">');
document.write('    <span>CINE Sci-fi</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="http(\service-stitcher-ipv4.clusters.pluto.tv/v1/stitch/embed/hls/channel/60c3472a51a2050008dad272/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=%7BUS_PRIVACY%7D&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&embedPartner=samsung-tvplus&gdprConsent=%7BTC_STRING%7D&gdpr=1\)">');
document.write('    <span>CINE THRILLERS</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="http(\service-stitcher-ipv4.clusters.pluto.tv/v1/stitch/embed/hls/channel/5f8ed4dbf6bb0800071ffbcb/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=%7BUS_PRIVACY%7D&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&embedPartner=samsung-tvplus&gdprConsent=%7BTC_STRING%7D&gdpr=1\)">');
document.write('    <span>CINE Polar</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\dc87c2cd402c4403a3f577a2be3925fd.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-fr_RakutenActionMovies/playlist.m3u8?ads.wurl_channel%3D447%26ads.wurl_name%3DRakutenActionMovies%26ads.psid%3D%7BPSID%7D%26ads.targetopt%3D%7BTARGETOPT%7D%26ads.app_domain%3D%7BAPP_DOMAIN%7D%26ads.app_name%3D%7BAPP_NAME%7D%26ads.coppa%3D0%26ads.consent%3D%7BTC_STRING%7D\)">');
document.write('    <span>Rakuten Action</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\rakuten-thriller-7-eu.rakuten.wurl.tv/playlist.m3u8\)">');
document.write('    <span>Rakuten THRILLER </span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\rakuten-romance-7-eu.rakuten.wurl.tv/playlist.m3u8\)">');
document.write('    <span>Rakuten Romance</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\e4d1581301dd446495286986116b1679.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-fr_RakutenComedyMovies/playlist.m3u8?ads.wurl_channel%3D448%26ads.wurl_name%3DRakutenComedyMovies%26ads.psid%3D%7BPSID%7D%26ads.targetopt%3D%7BTARGETOPT%7D%26ads.app_domain%3D%7BAPP_DOMAIN%7D%26ads.app_name%3D%7BAPP_NAME%7D%26ads.coppa%3D0%26ads.consent%3D%7BTC_STRING%7D\)">');
document.write('    <span>Rakuten Comedy</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\5b31b343db684f2d897b12cc1793defb.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-fr_RakutenTVShows/playlist.m3u8?ads.wurl_channel%3D449%26ads.wurl_name%3DRakutenTVShows%26ads.psid%3D%7BPSID%7D%26ads.targetopt%3D%7BTARGETOPT%7D%26ads.app_domain%3D%7BAPP_DOMAIN%7D%26ads.app_name%3D%7BAPP_NAME%7D%26ads.coppa%3D0%26ads.consent%3D%7BTC_STRING%7D\)">');
document.write('    <span>Rakuten Tv Show</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\rakuten-spotlight-7-eu.rakuten.wurl.tv/playlist.m3u8\)">');
document.write('    <span>Rakuten Spotlight</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\rakuten-topfree-7-eu.rakuten.wurl.tv/playlist.m3u8\)">');
document.write('    <span>Rakuten Cinema</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\43e98e0eaa9b4118b1b79e62f98cff7d.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-fr_RakutenFamily/playlist.m3u8?ads.wurl_channel%3D720%26ads.wurl_name%3DRakutenFamily%26ads.coppa%3D1%26ads.psid%3D%7BPSID%7D%26ads.targetopt%3D%7BTARGETOPT%7D%26ads.app_domain%3D%7BAPP_DOMAIN%7D%26ads.app_name%3D%7BAPP_NAME%7D%26ads.consent%3D%7BTC_STRING%7D\)">');
document.write('    <span>Rakuten Family</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\d2o63bkh2qz410.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/CineNanar-FR-prod/cinenanar/master.m3u8?ads.device_did=%7BPSID%7D&ads.device_dnt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.consent=%7BTC_STRING%7D\)">');
document.write('    <span>Ciné Ninar</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\d1jpd8j6nh8nwm.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-uuryop9dra2jr-prod/screamin/master.m3u8?ads.device_did=%7BPSID%7D&ads.device_dnt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.consent=%7BTC_STRING%7D\)">');
document.write('    <span>Scrimin</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\alchimie-krime-rakuten.amagi.tv/playlist.m3u8\)">');
document.write('    <span>Krime</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\dba2f9e98eb44a478946116c5e90e55b.mediatailor.us-east-1.amazonaws.com/v1/master/04fd913bb278d8775298c26fdca9d9841f37601f/Samsung-fr_WildSideTV/playlist.m3u8?ads.wurl_channel=871&ads.wurl_name=WildSideTV&ads.coppa=0&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.consent=%7BTC_STRING%7D\)">');
document.write('    <span>Wilde Side</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\service-stitcher-ipv4.clusters.pluto.tv/v1/stitch/embed/hls/channel/5f8ece1a89d79800072510e6/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=%7BUS_PRIVACY%7D&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&embedPartner=samsung-tvplus&gdprConsent=%7BTC_STRING%7D&gdpr=1\)">');
document.write('    <span>the asylum</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\mytimefrance-rakuten-samsung.amagi.tv/playlist.m3u8\)">');
document.write('    <span>My time movies</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\d2fih5ugbu4v3d.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-adwf5iz2j8r09-prod/run/rt_fr/rt_fr.m3u8?ads.device_did=%7BPSID%7D&ads.device_dnt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.consent=%7BTC_STRING%7D\)">');
document.write('    <span>Run time </span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\caec5a936f944a8d83ccb21f8266b684.mediatailor.us-east-1.amazonaws.com/v1/master/04fd913bb278d8775298c26fdca9d9841f37601f/Samsung-fr_BBCDrama/playlist.m3u8?ads.wurl_channel=946&ads.wurl_name=BBCDrama&ads.coppa=0&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.consent=%7BTC_STRING%7D\)">');
document.write('    <span>BBC Drama </span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\sofytv-samsungfr.amagi.tv/playlist.m3u8\)">');
document.write('    <span>Sofy Fr </span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\c3776ebb1c7742cb9c0191b41b8b2432.mediatailor.us-east-1.amazonaws.com/v1/master/04fd913bb278d8775298c26fdca9d9841f37601f/Samsung-fr_Brefcinema/playlist.m3u8?ads.wurl_channel=981&ads.wurl_name=Brefcinema&ads.coppa=0&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.consent=%7BTC_STRING%7D\)">');
document.write('    <span>BrefCinéma </span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\service-stitcher-ipv4.clusters.pluto.tv/v1/stitch/embed/hls/channel/61533b6334ba9b000763d7b1/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=%7BUS_PRIVACY%7D&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&embedPartner=samsung-tvplus&gdprConsent=%7BTC_STRING%7D&gdpr=1\)">');
document.write('    <span>Amour Gloire et beauté </span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\diqx5lyj19frh.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/Emotionelle-FR-prod/master.m3u8?ads.device_did%3D%7BPSID%7D%26ads.device_dnt%3D%7BTARGETOPT%7D%26ads.app_domain%3D%7BAPP_DOMAIN%7D%26ads.app_name%3D%7BAPP_NAME%7D\)">');
document.write('    <span>Émotionnel TV</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\dlfgnu48pa2lo.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-4do8qdzsxt6b6-prod/frequencenovelas/master.m3u8?ads.device_did=%7BPSID%7D&ads.device_dnt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.consent=%7BTC_STRING%7D\)">');
document.write('    <span>Fréquence Novelas</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\78088d9226df47fb95e3320920b08ad7.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-fr_StormcastNovelas/playlist.m3u8?ads.wurl_channel=613&ads.wurl_name=StormcastNovelas&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=0&ads.consent=%7BTC_STRING%7D\)">');
document.write('    <span>Stromcast </span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\40413a8d4fab4568b22187b5d7cd15c9.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-fr_Televisa/playlist.m3u8?ads.wurl_channel=820&ads.wurl_name=Televisa&ads.coppa=0&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.consent=%7BTC_STRING%7D\)">');
document.write('    <span>Televisa telenovelas</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\service-stitcher-ipv4.clusters.pluto.tv/v1/stitch/embed/hls/channel/5f914f9dccb4de0007df8bc4/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=%7BUS_PRIVACY%7D&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&embedPartner=samsung-tvplus&gdprConsent=%7BTC_STRING%7D&gdpr=1\)">');
document.write('    <span>Telenovela</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\iframe.dacast.com/b/15863/c/22707\)">');
document.write('    <span>IDF1 </span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\live-antenne-reunion.zeop.tv/live/c3eds/antreunihd/hls_fta/antreunihd.m3u8?location=ZEOP01\)">');
document.write('    <span>Antenna Réunion</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\service-stitcher-ipv4.clusters.pluto.tv/v1/stitch/embed/hls/channel/5f8ed52a62fa750007733239/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=%7BUS_PRIVACY%7D&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&embedPartner=samsung-tvplus&gdprConsent=%7BTC_STRING%7D&gdpr=1\)">');
document.write('    <span>Anime All day </span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\cdn-uw2-prod.tsv2.amagi.tv/linear/amg01596-gongnetworks-gong-samsungfr/playlist.m3u8?ads.did=%7BPSID%7D&ads.dnt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.tc_string=%7BTC_STRING%7D&ads.coppa=0\)">');
document.write('    <span>Gong </span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\detxaqhrw2ib7.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-qnsppao6j5uqn-prod/mtd/jt/mtd_jt.m3u8?ads.device_did=%7BPSID%7D&ads.device_dnt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.consent=%7BTC_STRING%7D\)">');
document.write('    <span>Jellytoon </span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\fda836df464945ceba2aaecfb771f934.mediatailor.us-east-1.amazonaws.com/v1/master/04fd913bb278d8775298c26fdca9d9841f37601f/Samsung-fr_XilamTV/playlist.m3u8?ads.wurl_channel=1005&ads.wurl_name=XilamTV&ads.coppa=1&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.consent=%7BTC_STRING%7D\)">');
document.write('    <span>Xilam Tv </span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\amuse-amuseanimation-2-fr.samsung.wurl.tv/3000.m3u8\)">');
document.write('    <span>Amuse Animation</span>');
document.write('  </li>');
document.write('  <li class="menu2" tabindex="0" onclick="https(\kedoo-supertoonstv-3-fr.samsung.wurl.tv/3000.m3u8\)">');
document.write('    <span>Supertoons Tv </span>');
document.write('  </li>');

} 
