function FUCKUTHIEF(){
document.write('<ul id="matchKey">');


document.write(' <li class="menu2" onclick=https("live-hls-web-aja.getaj.net/AJA/index.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/3x3lce2">');
document.write('   <span>aljazira tv</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("live-hls-web-ajm.getaj.net/AJM/index.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/3apfbwK">');
document.write('   <span>aljazira mubacher</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("live.alarabiya.net/alarabiapublish/alarabiya.smil/playlist.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/3owObkh">');
document.write('   <span>alarabia</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("shls-hadath-prod-dub.shahid.net/out/v1/0e1a306399c346faac4226aa0858f99b/index.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/36tclpF">');
document.write('   <span>alhadath</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("shls-asharq-prod-dub.shahid.net/out/v1/3b6b4902cf8747a28619411239584002/index.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/37Zwnsi">');
document.write('   <span>al sharq</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("al-ekhbaria-prod-dub.shahid.net/out/v1/d443f3203b444032896e3233cb6eaa84/index.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/3PIOcAp">');
document.write('   <span>al ekhbaria</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("almamlka-live.ercdn.net/almamlka/almamlka.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/2MphckC">');
document.write('   <span>almamlaka</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("stream.skynewsarabia.com/hls/sna.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/39e3Wuy">');
document.write('   <span>sky news ar</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("vs-hls-pushb-ww-live.akamaized.net/x=3/i=urn:bbc:pips:service:bbc_arabic_tv/t=3840/v=pv14/b=5070016/main.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/3r9w6dH">');
document.write('   <span>bbc ar</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("live2.alalam.ir/live/Alalam/index.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/3Nv4rim">');
document.write('   <span>alalam</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("cdg8.edge.technocdn.com/watantv/live/chunks.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/3GP3O1f">');
document.write('   <span>alwatan</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=http("149.62.183.214:8000/play/a01g/index.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/2Yykzs0">');
document.write('   <span>France 24 ar</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("dwamdstream103.akamaized.net/hls/live/2015526/dwstream103/index.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/3j27VuW">');
document.write('   <span>dw arabi</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("tv-trtarabi.live.trt.com.tr/master.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/36u7Xqk">');
document.write('   <span>trt arabi</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("alaraby.cdn.octivid.com/alaraby/smil:alaraby.stream.smil/playlist.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/3oBqTJR">');
document.write('   <span>alarabi</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("https://cdn.bestream.io:19360/alqanat9/alqanat9.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/3vlaUoV">');
document.write('   <span>alqanat 9</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("lmdstrm.cdn.octivid.com/mayadeen-live/smil:mayadeen.smil/chunklist.m3u8")>');
document.write('   <img title="news" src="https://upload.wikimedia.org/wikipedia/ar/0/04/%D8%B4%D8%B9%D8%A7%D8%B1_%D9%82%D9%86%D8%A7%D8%A9_%D8%A7%D9%84%D9%85%D9%8A%D8%A7%D8%AF%D9%8A%D9%86.jpg">');
document.write('   <span>almayadin</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("mn-nl.mncdn.com/alhiwar_live/smil:alhiwar.smil/chunklist.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/2YtPfe6">');
document.write('   <span>alhiwar</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("mbn-ingest-worldsafe.akamaized.net/hls/live/2038900/MBN_Alhurra_Worldsafe_HLS/master.m3u8")>');
document.write('   <img title="news" src="https://arbne.ws/3MoHfkW">');
document.write('   <span>alhurra</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("mbn-ingest-worldsafe.akamaized.net/hls/live/2038899/MBN_Iraq_Worldsafe_HLS/master.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/3MiWGuT">');
document.write('   <span>alhurra iraq</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("mn-nl.mncdn.com/elsharq_live/live/chunklist.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/3Q47QXN">');
document.write('   <span>alsharq</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("mn-nl.mncdn.com/khalij/khalij/chunklist.m3u8")>');
document.write('   <img title="news" src="https://bit.ly/3N2JfzU">');
document.write('   <span>alkhalij</span>');
document.write(' </li>');
document.write(' <li class="menu2" onclick=https("elahmad-com-1a.herokuapp.com/elahmad.php/https://rt-arb.rttv.com/live/rtarab/playlist_1600Kb.m3u8")>');
document.write('   <img title="news" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Russia-today-logo.svg/1200px-Russia-today-logo.svg.png">');
document.write('   <span>RT arab </span>');
document.write(' </li>');



document.write('</ul>');
} 
